// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#ifndef PROTOBUF_common_2eproto__INCLUDED
#define PROTOBUF_common_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace common {
class indirect_register_t;
class indirect_register_tDefaultTypeInternal;
extern indirect_register_tDefaultTypeInternal _indirect_register_t_default_instance_;
class memory_pol;
class memory_polDefaultTypeInternal;
extern memory_polDefaultTypeInternal _memory_pol_default_instance_;
class memory_t;
class memory_tDefaultTypeInternal;
extern memory_tDefaultTypeInternal _memory_t_default_instance_;
class register_t;
class register_tDefaultTypeInternal;
extern register_tDefaultTypeInternal _register_t_default_instance_;
class register_value_t;
class register_value_tDefaultTypeInternal;
extern register_value_tDefaultTypeInternal _register_value_t_default_instance_;
}  // namespace common

namespace common {

namespace protobuf_common_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_common_2eproto

enum smt_result {
  UNKNOWN = 0,
  SAT = 1,
  UNSAT = 2,
  TIMEOUT = 3
};
bool smt_result_IsValid(int value);
const smt_result smt_result_MIN = UNKNOWN;
const smt_result smt_result_MAX = TIMEOUT;
const int smt_result_ARRAYSIZE = smt_result_MAX + 1;

const ::google::protobuf::EnumDescriptor* smt_result_descriptor();
inline const ::std::string& smt_result_Name(smt_result value) {
  return ::google::protobuf::internal::NameOfEnum(
    smt_result_descriptor(), value);
}
inline bool smt_result_Parse(
    const ::std::string& name, smt_result* value) {
  return ::google::protobuf::internal::ParseNamedEnum<smt_result>(
    smt_result_descriptor(), name, value);
}
enum tracing_action {
  SKIP = 0,
  INTO = 1
};
bool tracing_action_IsValid(int value);
const tracing_action tracing_action_MIN = SKIP;
const tracing_action tracing_action_MAX = INTO;
const int tracing_action_ARRAYSIZE = tracing_action_MAX + 1;

const ::google::protobuf::EnumDescriptor* tracing_action_descriptor();
inline const ::std::string& tracing_action_Name(tracing_action value) {
  return ::google::protobuf::internal::NameOfEnum(
    tracing_action_descriptor(), value);
}
inline bool tracing_action_Parse(
    const ::std::string& name, tracing_action* value) {
  return ::google::protobuf::internal::ParseNamedEnum<tracing_action>(
    tracing_action_descriptor(), name, value);
}
enum action {
  DEFAULT = 0,
  PATCH = 1,
  CONC = 2,
  SYMB = 3,
  LOGIC = 4,
  IGNORE = 5
};
bool action_IsValid(int value);
const action action_MIN = DEFAULT;
const action action_MAX = IGNORE;
const int action_ARRAYSIZE = action_MAX + 1;

const ::google::protobuf::EnumDescriptor* action_descriptor();
inline const ::std::string& action_Name(action value) {
  return ::google::protobuf::internal::NameOfEnum(
    action_descriptor(), value);
}
inline bool action_Parse(
    const ::std::string& name, action* value) {
  return ::google::protobuf::internal::ParseNamedEnum<action>(
    action_descriptor(), name, value);
}
enum call_convention_t {
  UNKNOWN_CVT = 0,
  CDECL = 1,
  FASTCALL = 2,
  STDCALL = 3,
  THISCALL = 4
};
bool call_convention_t_IsValid(int value);
const call_convention_t call_convention_t_MIN = UNKNOWN_CVT;
const call_convention_t call_convention_t_MAX = THISCALL;
const int call_convention_t_ARRAYSIZE = call_convention_t_MAX + 1;

const ::google::protobuf::EnumDescriptor* call_convention_t_descriptor();
inline const ::std::string& call_convention_t_Name(call_convention_t value) {
  return ::google::protobuf::internal::NameOfEnum(
    call_convention_t_descriptor(), value);
}
inline bool call_convention_t_Parse(
    const ::std::string& name, call_convention_t* value) {
  return ::google::protobuf::internal::ParseNamedEnum<call_convention_t>(
    call_convention_t_descriptor(), name, value);
}
enum ir_kind_t {
  DBA = 1,
  BAP = 2,
  MIASM = 3
};
bool ir_kind_t_IsValid(int value);
const ir_kind_t ir_kind_t_MIN = DBA;
const ir_kind_t ir_kind_t_MAX = MIASM;
const int ir_kind_t_ARRAYSIZE = ir_kind_t_MAX + 1;

const ::google::protobuf::EnumDescriptor* ir_kind_t_descriptor();
inline const ::std::string& ir_kind_t_Name(ir_kind_t value) {
  return ::google::protobuf::internal::NameOfEnum(
    ir_kind_t_descriptor(), value);
}
inline bool ir_kind_t_Parse(
    const ::std::string& name, ir_kind_t* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ir_kind_t>(
    ir_kind_t_descriptor(), name, value);
}
enum solver_t {
  Z3 = 1,
  BOOLECTOR = 2,
  CVC4 = 3,
  YICES = 4
};
bool solver_t_IsValid(int value);
const solver_t solver_t_MIN = Z3;
const solver_t solver_t_MAX = YICES;
const int solver_t_ARRAYSIZE = solver_t_MAX + 1;

const ::google::protobuf::EnumDescriptor* solver_t_descriptor();
inline const ::std::string& solver_t_Name(solver_t value) {
  return ::google::protobuf::internal::NameOfEnum(
    solver_t_descriptor(), value);
}
inline bool solver_t_Parse(
    const ::std::string& name, solver_t* value) {
  return ::google::protobuf::internal::ParseNamedEnum<solver_t>(
    solver_t_descriptor(), name, value);
}
enum analysis_direction_t {
  FORWARD = 1,
  BACKWARD = 2
};
bool analysis_direction_t_IsValid(int value);
const analysis_direction_t analysis_direction_t_MIN = FORWARD;
const analysis_direction_t analysis_direction_t_MAX = BACKWARD;
const int analysis_direction_t_ARRAYSIZE = analysis_direction_t_MAX + 1;

const ::google::protobuf::EnumDescriptor* analysis_direction_t_descriptor();
inline const ::std::string& analysis_direction_t_Name(analysis_direction_t value) {
  return ::google::protobuf::internal::NameOfEnum(
    analysis_direction_t_descriptor(), value);
}
inline bool analysis_direction_t_Parse(
    const ::std::string& name, analysis_direction_t* value) {
  return ::google::protobuf::internal::ParseNamedEnum<analysis_direction_t>(
    analysis_direction_t_descriptor(), name, value);
}
enum proto_size_t {
  INVALID_SIZE = 0,
  BIT8 = 1,
  BIT16 = 2,
  BIT32 = 3,
  BIT64 = 4,
  BIT80 = 5,
  BIT128 = 6,
  BIT256 = 7
};
bool proto_size_t_IsValid(int value);
const proto_size_t proto_size_t_MIN = INVALID_SIZE;
const proto_size_t proto_size_t_MAX = BIT256;
const int proto_size_t_ARRAYSIZE = proto_size_t_MAX + 1;

const ::google::protobuf::EnumDescriptor* proto_size_t_descriptor();
inline const ::std::string& proto_size_t_Name(proto_size_t value) {
  return ::google::protobuf::internal::NameOfEnum(
    proto_size_t_descriptor(), value);
}
inline bool proto_size_t_Parse(
    const ::std::string& name, proto_size_t* value) {
  return ::google::protobuf::internal::ParseNamedEnum<proto_size_t>(
    proto_size_t_descriptor(), name, value);
}
// ===================================================================

class register_value_t : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:common.register_value_t) */ {
 public:
  register_value_t();
  virtual ~register_value_t();

  register_value_t(const register_value_t& from);

  inline register_value_t& operator=(const register_value_t& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const register_value_t& default_instance();

  enum ValueCntCase {
    kValue8 = 2,
    kValue16 = 3,
    kValue32 = 4,
    kValue64 = 5,
    kValue80 = 6,
    kValue128 = 7,
    kValue256 = 8,
    VALUE_CNT_NOT_SET = 0,
  };

  static inline const register_value_t* internal_default_instance() {
    return reinterpret_cast<const register_value_t*>(
               &_register_value_t_default_instance_);
  }

  void Swap(register_value_t* other);

  // implements Message ----------------------------------------------

  inline register_value_t* New() const PROTOBUF_FINAL { return New(NULL); }

  register_value_t* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const register_value_t& from);
  void MergeFrom(const register_value_t& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(register_value_t* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .common.proto_size_t typeid = 1;
  bool has_typeid_() const;
  void clear_typeid_();
  static const int kTypeidFieldNumber = 1;
  ::common::proto_size_t typeid_() const;
  void set_typeid_(::common::proto_size_t value);

  // optional uint32 value_8 = 2;
  bool has_value_8() const;
  void clear_value_8();
  static const int kValue8FieldNumber = 2;
  ::google::protobuf::uint32 value_8() const;
  void set_value_8(::google::protobuf::uint32 value);

  // optional uint32 value_16 = 3;
  bool has_value_16() const;
  void clear_value_16();
  static const int kValue16FieldNumber = 3;
  ::google::protobuf::uint32 value_16() const;
  void set_value_16(::google::protobuf::uint32 value);

  // optional uint32 value_32 = 4;
  bool has_value_32() const;
  void clear_value_32();
  static const int kValue32FieldNumber = 4;
  ::google::protobuf::uint32 value_32() const;
  void set_value_32(::google::protobuf::uint32 value);

  // optional uint64 value_64 = 5;
  bool has_value_64() const;
  void clear_value_64();
  static const int kValue64FieldNumber = 5;
  ::google::protobuf::uint64 value_64() const;
  void set_value_64(::google::protobuf::uint64 value);

  // optional bytes value_80 = 6;
  bool has_value_80() const;
  void clear_value_80();
  static const int kValue80FieldNumber = 6;
  const ::std::string& value_80() const;
  void set_value_80(const ::std::string& value);
  #if LANG_CXX11
  void set_value_80(::std::string&& value);
  #endif
  void set_value_80(const char* value);
  void set_value_80(const void* value, size_t size);
  ::std::string* mutable_value_80();
  ::std::string* release_value_80();
  void set_allocated_value_80(::std::string* value_80);

  // optional bytes value_128 = 7;
  bool has_value_128() const;
  void clear_value_128();
  static const int kValue128FieldNumber = 7;
  const ::std::string& value_128() const;
  void set_value_128(const ::std::string& value);
  #if LANG_CXX11
  void set_value_128(::std::string&& value);
  #endif
  void set_value_128(const char* value);
  void set_value_128(const void* value, size_t size);
  ::std::string* mutable_value_128();
  ::std::string* release_value_128();
  void set_allocated_value_128(::std::string* value_128);

  // optional bytes value_256 = 8;
  bool has_value_256() const;
  void clear_value_256();
  static const int kValue256FieldNumber = 8;
  const ::std::string& value_256() const;
  void set_value_256(const ::std::string& value);
  #if LANG_CXX11
  void set_value_256(::std::string&& value);
  #endif
  void set_value_256(const char* value);
  void set_value_256(const void* value, size_t size);
  ::std::string* mutable_value_256();
  ::std::string* release_value_256();
  void set_allocated_value_256(::std::string* value_256);

  ValueCntCase value_cnt_case() const;
  // @@protoc_insertion_point(class_scope:common.register_value_t)
 private:
  void set_has_typeid_();
  void clear_has_typeid_();
  void set_has_value_8();
  void set_has_value_16();
  void set_has_value_32();
  void set_has_value_64();
  void set_has_value_80();
  void set_has_value_128();
  void set_has_value_256();

  inline bool has_value_cnt() const;
  void clear_value_cnt();
  inline void clear_has_value_cnt();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  int typeid__;
  union ValueCntUnion {
    ValueCntUnion() {}
    ::google::protobuf::uint32 value_8_;
    ::google::protobuf::uint32 value_16_;
    ::google::protobuf::uint32 value_32_;
    ::google::protobuf::uint64 value_64_;
    ::google::protobuf::internal::ArenaStringPtr value_80_;
    ::google::protobuf::internal::ArenaStringPtr value_128_;
    ::google::protobuf::internal::ArenaStringPtr value_256_;
  } value_cnt_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct  protobuf_common_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class register_t : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:common.register_t) */ {
 public:
  register_t();
  virtual ~register_t();

  register_t(const register_t& from);

  inline register_t& operator=(const register_t& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const register_t& default_instance();

  static inline const register_t* internal_default_instance() {
    return reinterpret_cast<const register_t*>(
               &_register_t_default_instance_);
  }

  void Swap(register_t* other);

  // implements Message ----------------------------------------------

  inline register_t* New() const PROTOBUF_FINAL { return New(NULL); }

  register_t* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const register_t& from);
  void MergeFrom(const register_t& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(register_t* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required .common.register_value_t value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::common::register_value_t& value() const;
  ::common::register_value_t* mutable_value();
  ::common::register_value_t* release_value();
  void set_allocated_value(::common::register_value_t* value);

  // @@protoc_insertion_point(class_scope:common.register_t)
 private:
  void set_has_name();
  void clear_has_name();
  void set_has_value();
  void clear_has_value();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::common::register_value_t* value_;
  friend struct  protobuf_common_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class memory_t : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:common.memory_t) */ {
 public:
  memory_t();
  virtual ~memory_t();

  memory_t(const memory_t& from);

  inline memory_t& operator=(const memory_t& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const memory_t& default_instance();

  static inline const memory_t* internal_default_instance() {
    return reinterpret_cast<const memory_t*>(
               &_memory_t_default_instance_);
  }

  void Swap(memory_t* other);

  // implements Message ----------------------------------------------

  inline memory_t* New() const PROTOBUF_FINAL { return New(NULL); }

  memory_t* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const memory_t& from);
  void MergeFrom(const memory_t& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(memory_t* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const void* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // required uint64 addr = 1;
  bool has_addr() const;
  void clear_addr();
  static const int kAddrFieldNumber = 1;
  ::google::protobuf::uint64 addr() const;
  void set_addr(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:common.memory_t)
 private:
  void set_has_addr();
  void clear_has_addr();
  void set_has_value();
  void clear_has_value();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  ::google::protobuf::uint64 addr_;
  friend struct  protobuf_common_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class indirect_register_t : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:common.indirect_register_t) */ {
 public:
  indirect_register_t();
  virtual ~indirect_register_t();

  indirect_register_t(const indirect_register_t& from);

  inline indirect_register_t& operator=(const indirect_register_t& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const indirect_register_t& default_instance();

  static inline const indirect_register_t* internal_default_instance() {
    return reinterpret_cast<const indirect_register_t*>(
               &_indirect_register_t_default_instance_);
  }

  void Swap(indirect_register_t* other);

  // implements Message ----------------------------------------------

  inline indirect_register_t* New() const PROTOBUF_FINAL { return New(NULL); }

  indirect_register_t* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const indirect_register_t& from);
  void MergeFrom(const indirect_register_t& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(indirect_register_t* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required bytes value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const void* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:common.indirect_register_t)
 private:
  void set_has_name();
  void clear_has_name();
  void set_has_value();
  void clear_has_value();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  friend struct  protobuf_common_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class memory_pol : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:common.memory_pol) */ {
 public:
  memory_pol();
  virtual ~memory_pol();

  memory_pol(const memory_pol& from);

  inline memory_pol& operator=(const memory_pol& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const memory_pol& default_instance();

  static inline const memory_pol* internal_default_instance() {
    return reinterpret_cast<const memory_pol*>(
               &_memory_pol_default_instance_);
  }

  void Swap(memory_pol* other);

  // implements Message ----------------------------------------------

  inline memory_pol* New() const PROTOBUF_FINAL { return New(NULL); }

  memory_pol* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const memory_pol& from);
  void MergeFrom(const memory_pol& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(memory_pol* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .common.action addr = 1 [default = DEFAULT];
  bool has_addr() const;
  void clear_addr();
  static const int kAddrFieldNumber = 1;
  ::common::action addr() const;
  void set_addr(::common::action value);

  // optional .common.action value = 2 [default = DEFAULT];
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  ::common::action value() const;
  void set_value(::common::action value);

  // @@protoc_insertion_point(class_scope:common.memory_pol)
 private:
  void set_has_addr();
  void clear_has_addr();
  void set_has_value();
  void clear_has_value();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  int addr_;
  int value_;
  friend struct  protobuf_common_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// register_value_t

// required .common.proto_size_t typeid = 1;
inline bool register_value_t::has_typeid_() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void register_value_t::set_has_typeid_() {
  _has_bits_[0] |= 0x00000001u;
}
inline void register_value_t::clear_has_typeid_() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void register_value_t::clear_typeid_() {
  typeid__ = 0;
  clear_has_typeid_();
}
inline ::common::proto_size_t register_value_t::typeid_() const {
  // @@protoc_insertion_point(field_get:common.register_value_t.typeid)
  return static_cast< ::common::proto_size_t >(typeid__);
}
inline void register_value_t::set_typeid_(::common::proto_size_t value) {
  assert(::common::proto_size_t_IsValid(value));
  set_has_typeid_();
  typeid__ = value;
  // @@protoc_insertion_point(field_set:common.register_value_t.typeid)
}

// optional uint32 value_8 = 2;
inline bool register_value_t::has_value_8() const {
  return value_cnt_case() == kValue8;
}
inline void register_value_t::set_has_value_8() {
  _oneof_case_[0] = kValue8;
}
inline void register_value_t::clear_value_8() {
  if (has_value_8()) {
    value_cnt_.value_8_ = 0u;
    clear_has_value_cnt();
  }
}
inline ::google::protobuf::uint32 register_value_t::value_8() const {
  // @@protoc_insertion_point(field_get:common.register_value_t.value_8)
  if (has_value_8()) {
    return value_cnt_.value_8_;
  }
  return 0u;
}
inline void register_value_t::set_value_8(::google::protobuf::uint32 value) {
  if (!has_value_8()) {
    clear_value_cnt();
    set_has_value_8();
  }
  value_cnt_.value_8_ = value;
  // @@protoc_insertion_point(field_set:common.register_value_t.value_8)
}

// optional uint32 value_16 = 3;
inline bool register_value_t::has_value_16() const {
  return value_cnt_case() == kValue16;
}
inline void register_value_t::set_has_value_16() {
  _oneof_case_[0] = kValue16;
}
inline void register_value_t::clear_value_16() {
  if (has_value_16()) {
    value_cnt_.value_16_ = 0u;
    clear_has_value_cnt();
  }
}
inline ::google::protobuf::uint32 register_value_t::value_16() const {
  // @@protoc_insertion_point(field_get:common.register_value_t.value_16)
  if (has_value_16()) {
    return value_cnt_.value_16_;
  }
  return 0u;
}
inline void register_value_t::set_value_16(::google::protobuf::uint32 value) {
  if (!has_value_16()) {
    clear_value_cnt();
    set_has_value_16();
  }
  value_cnt_.value_16_ = value;
  // @@protoc_insertion_point(field_set:common.register_value_t.value_16)
}

// optional uint32 value_32 = 4;
inline bool register_value_t::has_value_32() const {
  return value_cnt_case() == kValue32;
}
inline void register_value_t::set_has_value_32() {
  _oneof_case_[0] = kValue32;
}
inline void register_value_t::clear_value_32() {
  if (has_value_32()) {
    value_cnt_.value_32_ = 0u;
    clear_has_value_cnt();
  }
}
inline ::google::protobuf::uint32 register_value_t::value_32() const {
  // @@protoc_insertion_point(field_get:common.register_value_t.value_32)
  if (has_value_32()) {
    return value_cnt_.value_32_;
  }
  return 0u;
}
inline void register_value_t::set_value_32(::google::protobuf::uint32 value) {
  if (!has_value_32()) {
    clear_value_cnt();
    set_has_value_32();
  }
  value_cnt_.value_32_ = value;
  // @@protoc_insertion_point(field_set:common.register_value_t.value_32)
}

// optional uint64 value_64 = 5;
inline bool register_value_t::has_value_64() const {
  return value_cnt_case() == kValue64;
}
inline void register_value_t::set_has_value_64() {
  _oneof_case_[0] = kValue64;
}
inline void register_value_t::clear_value_64() {
  if (has_value_64()) {
    value_cnt_.value_64_ = GOOGLE_ULONGLONG(0);
    clear_has_value_cnt();
  }
}
inline ::google::protobuf::uint64 register_value_t::value_64() const {
  // @@protoc_insertion_point(field_get:common.register_value_t.value_64)
  if (has_value_64()) {
    return value_cnt_.value_64_;
  }
  return GOOGLE_ULONGLONG(0);
}
inline void register_value_t::set_value_64(::google::protobuf::uint64 value) {
  if (!has_value_64()) {
    clear_value_cnt();
    set_has_value_64();
  }
  value_cnt_.value_64_ = value;
  // @@protoc_insertion_point(field_set:common.register_value_t.value_64)
}

// optional bytes value_80 = 6;
inline bool register_value_t::has_value_80() const {
  return value_cnt_case() == kValue80;
}
inline void register_value_t::set_has_value_80() {
  _oneof_case_[0] = kValue80;
}
inline void register_value_t::clear_value_80() {
  if (has_value_80()) {
    value_cnt_.value_80_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_value_cnt();
  }
}
inline const ::std::string& register_value_t::value_80() const {
  // @@protoc_insertion_point(field_get:common.register_value_t.value_80)
  if (has_value_80()) {
    return value_cnt_.value_80_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
inline void register_value_t::set_value_80(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:common.register_value_t.value_80)
  if (!has_value_80()) {
    clear_value_cnt();
    set_has_value_80();
    value_cnt_.value_80_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_cnt_.value_80_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:common.register_value_t.value_80)
}
#if LANG_CXX11
inline void register_value_t::set_value_80(::std::string&& value) {
  // @@protoc_insertion_point(field_set:common.register_value_t.value_80)
  if (!has_value_80()) {
    clear_value_cnt();
    set_has_value_80();
    value_cnt_.value_80_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_cnt_.value_80_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:common.register_value_t.value_80)
}
#endif
inline void register_value_t::set_value_80(const char* value) {
  if (!has_value_80()) {
    clear_value_cnt();
    set_has_value_80();
    value_cnt_.value_80_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_cnt_.value_80_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:common.register_value_t.value_80)
}
inline void register_value_t::set_value_80(const void* value, size_t size) {
  if (!has_value_80()) {
    clear_value_cnt();
    set_has_value_80();
    value_cnt_.value_80_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_cnt_.value_80_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:common.register_value_t.value_80)
}
inline ::std::string* register_value_t::mutable_value_80() {
  if (!has_value_80()) {
    clear_value_cnt();
    set_has_value_80();
    value_cnt_.value_80_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:common.register_value_t.value_80)
  return value_cnt_.value_80_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* register_value_t::release_value_80() {
  // @@protoc_insertion_point(field_release:common.register_value_t.value_80)
  if (has_value_80()) {
    clear_has_value_cnt();
    return value_cnt_.value_80_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
inline void register_value_t::set_allocated_value_80(::std::string* value_80) {
  if (!has_value_80()) {
    value_cnt_.value_80_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_value_cnt();
  if (value_80 != NULL) {
    set_has_value_80();
    value_cnt_.value_80_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        value_80);
  }
  // @@protoc_insertion_point(field_set_allocated:common.register_value_t.value_80)
}

// optional bytes value_128 = 7;
inline bool register_value_t::has_value_128() const {
  return value_cnt_case() == kValue128;
}
inline void register_value_t::set_has_value_128() {
  _oneof_case_[0] = kValue128;
}
inline void register_value_t::clear_value_128() {
  if (has_value_128()) {
    value_cnt_.value_128_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_value_cnt();
  }
}
inline const ::std::string& register_value_t::value_128() const {
  // @@protoc_insertion_point(field_get:common.register_value_t.value_128)
  if (has_value_128()) {
    return value_cnt_.value_128_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
inline void register_value_t::set_value_128(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:common.register_value_t.value_128)
  if (!has_value_128()) {
    clear_value_cnt();
    set_has_value_128();
    value_cnt_.value_128_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_cnt_.value_128_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:common.register_value_t.value_128)
}
#if LANG_CXX11
inline void register_value_t::set_value_128(::std::string&& value) {
  // @@protoc_insertion_point(field_set:common.register_value_t.value_128)
  if (!has_value_128()) {
    clear_value_cnt();
    set_has_value_128();
    value_cnt_.value_128_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_cnt_.value_128_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:common.register_value_t.value_128)
}
#endif
inline void register_value_t::set_value_128(const char* value) {
  if (!has_value_128()) {
    clear_value_cnt();
    set_has_value_128();
    value_cnt_.value_128_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_cnt_.value_128_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:common.register_value_t.value_128)
}
inline void register_value_t::set_value_128(const void* value, size_t size) {
  if (!has_value_128()) {
    clear_value_cnt();
    set_has_value_128();
    value_cnt_.value_128_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_cnt_.value_128_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:common.register_value_t.value_128)
}
inline ::std::string* register_value_t::mutable_value_128() {
  if (!has_value_128()) {
    clear_value_cnt();
    set_has_value_128();
    value_cnt_.value_128_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:common.register_value_t.value_128)
  return value_cnt_.value_128_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* register_value_t::release_value_128() {
  // @@protoc_insertion_point(field_release:common.register_value_t.value_128)
  if (has_value_128()) {
    clear_has_value_cnt();
    return value_cnt_.value_128_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
inline void register_value_t::set_allocated_value_128(::std::string* value_128) {
  if (!has_value_128()) {
    value_cnt_.value_128_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_value_cnt();
  if (value_128 != NULL) {
    set_has_value_128();
    value_cnt_.value_128_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        value_128);
  }
  // @@protoc_insertion_point(field_set_allocated:common.register_value_t.value_128)
}

// optional bytes value_256 = 8;
inline bool register_value_t::has_value_256() const {
  return value_cnt_case() == kValue256;
}
inline void register_value_t::set_has_value_256() {
  _oneof_case_[0] = kValue256;
}
inline void register_value_t::clear_value_256() {
  if (has_value_256()) {
    value_cnt_.value_256_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_value_cnt();
  }
}
inline const ::std::string& register_value_t::value_256() const {
  // @@protoc_insertion_point(field_get:common.register_value_t.value_256)
  if (has_value_256()) {
    return value_cnt_.value_256_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
inline void register_value_t::set_value_256(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:common.register_value_t.value_256)
  if (!has_value_256()) {
    clear_value_cnt();
    set_has_value_256();
    value_cnt_.value_256_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_cnt_.value_256_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:common.register_value_t.value_256)
}
#if LANG_CXX11
inline void register_value_t::set_value_256(::std::string&& value) {
  // @@protoc_insertion_point(field_set:common.register_value_t.value_256)
  if (!has_value_256()) {
    clear_value_cnt();
    set_has_value_256();
    value_cnt_.value_256_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_cnt_.value_256_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:common.register_value_t.value_256)
}
#endif
inline void register_value_t::set_value_256(const char* value) {
  if (!has_value_256()) {
    clear_value_cnt();
    set_has_value_256();
    value_cnt_.value_256_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_cnt_.value_256_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:common.register_value_t.value_256)
}
inline void register_value_t::set_value_256(const void* value, size_t size) {
  if (!has_value_256()) {
    clear_value_cnt();
    set_has_value_256();
    value_cnt_.value_256_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_cnt_.value_256_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:common.register_value_t.value_256)
}
inline ::std::string* register_value_t::mutable_value_256() {
  if (!has_value_256()) {
    clear_value_cnt();
    set_has_value_256();
    value_cnt_.value_256_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:common.register_value_t.value_256)
  return value_cnt_.value_256_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* register_value_t::release_value_256() {
  // @@protoc_insertion_point(field_release:common.register_value_t.value_256)
  if (has_value_256()) {
    clear_has_value_cnt();
    return value_cnt_.value_256_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
inline void register_value_t::set_allocated_value_256(::std::string* value_256) {
  if (!has_value_256()) {
    value_cnt_.value_256_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_value_cnt();
  if (value_256 != NULL) {
    set_has_value_256();
    value_cnt_.value_256_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        value_256);
  }
  // @@protoc_insertion_point(field_set_allocated:common.register_value_t.value_256)
}

inline bool register_value_t::has_value_cnt() const {
  return value_cnt_case() != VALUE_CNT_NOT_SET;
}
inline void register_value_t::clear_has_value_cnt() {
  _oneof_case_[0] = VALUE_CNT_NOT_SET;
}
inline register_value_t::ValueCntCase register_value_t::value_cnt_case() const {
  return register_value_t::ValueCntCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// register_t

// required string name = 1;
inline bool register_t::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void register_t::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void register_t::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void register_t::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& register_t::name() const {
  // @@protoc_insertion_point(field_get:common.register_t.name)
  return name_.GetNoArena();
}
inline void register_t::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:common.register_t.name)
}
#if LANG_CXX11
inline void register_t::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:common.register_t.name)
}
#endif
inline void register_t::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:common.register_t.name)
}
inline void register_t::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:common.register_t.name)
}
inline ::std::string* register_t::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:common.register_t.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* register_t::release_name() {
  // @@protoc_insertion_point(field_release:common.register_t.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void register_t::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:common.register_t.name)
}

// required .common.register_value_t value = 2;
inline bool register_t::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void register_t::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void register_t::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void register_t::clear_value() {
  if (value_ != NULL) value_->::common::register_value_t::Clear();
  clear_has_value();
}
inline const ::common::register_value_t& register_t::value() const {
  // @@protoc_insertion_point(field_get:common.register_t.value)
  return value_ != NULL ? *value_
                         : *::common::register_value_t::internal_default_instance();
}
inline ::common::register_value_t* register_t::mutable_value() {
  set_has_value();
  if (value_ == NULL) {
    value_ = new ::common::register_value_t;
  }
  // @@protoc_insertion_point(field_mutable:common.register_t.value)
  return value_;
}
inline ::common::register_value_t* register_t::release_value() {
  // @@protoc_insertion_point(field_release:common.register_t.value)
  clear_has_value();
  ::common::register_value_t* temp = value_;
  value_ = NULL;
  return temp;
}
inline void register_t::set_allocated_value(::common::register_value_t* value) {
  delete value_;
  value_ = value;
  if (value) {
    set_has_value();
  } else {
    clear_has_value();
  }
  // @@protoc_insertion_point(field_set_allocated:common.register_t.value)
}

// -------------------------------------------------------------------

// memory_t

// required uint64 addr = 1;
inline bool memory_t::has_addr() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void memory_t::set_has_addr() {
  _has_bits_[0] |= 0x00000002u;
}
inline void memory_t::clear_has_addr() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void memory_t::clear_addr() {
  addr_ = GOOGLE_ULONGLONG(0);
  clear_has_addr();
}
inline ::google::protobuf::uint64 memory_t::addr() const {
  // @@protoc_insertion_point(field_get:common.memory_t.addr)
  return addr_;
}
inline void memory_t::set_addr(::google::protobuf::uint64 value) {
  set_has_addr();
  addr_ = value;
  // @@protoc_insertion_point(field_set:common.memory_t.addr)
}

// required bytes value = 2;
inline bool memory_t::has_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void memory_t::set_has_value() {
  _has_bits_[0] |= 0x00000001u;
}
inline void memory_t::clear_has_value() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void memory_t::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
inline const ::std::string& memory_t::value() const {
  // @@protoc_insertion_point(field_get:common.memory_t.value)
  return value_.GetNoArena();
}
inline void memory_t::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:common.memory_t.value)
}
#if LANG_CXX11
inline void memory_t::set_value(::std::string&& value) {
  set_has_value();
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:common.memory_t.value)
}
#endif
inline void memory_t::set_value(const char* value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:common.memory_t.value)
}
inline void memory_t::set_value(const void* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:common.memory_t.value)
}
inline ::std::string* memory_t::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:common.memory_t.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* memory_t::release_value() {
  // @@protoc_insertion_point(field_release:common.memory_t.value)
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void memory_t::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:common.memory_t.value)
}

// -------------------------------------------------------------------

// indirect_register_t

// required string name = 1;
inline bool indirect_register_t::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void indirect_register_t::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void indirect_register_t::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void indirect_register_t::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& indirect_register_t::name() const {
  // @@protoc_insertion_point(field_get:common.indirect_register_t.name)
  return name_.GetNoArena();
}
inline void indirect_register_t::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:common.indirect_register_t.name)
}
#if LANG_CXX11
inline void indirect_register_t::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:common.indirect_register_t.name)
}
#endif
inline void indirect_register_t::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:common.indirect_register_t.name)
}
inline void indirect_register_t::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:common.indirect_register_t.name)
}
inline ::std::string* indirect_register_t::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:common.indirect_register_t.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* indirect_register_t::release_name() {
  // @@protoc_insertion_point(field_release:common.indirect_register_t.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void indirect_register_t::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:common.indirect_register_t.name)
}

// required bytes value = 2;
inline bool indirect_register_t::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void indirect_register_t::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void indirect_register_t::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void indirect_register_t::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
inline const ::std::string& indirect_register_t::value() const {
  // @@protoc_insertion_point(field_get:common.indirect_register_t.value)
  return value_.GetNoArena();
}
inline void indirect_register_t::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:common.indirect_register_t.value)
}
#if LANG_CXX11
inline void indirect_register_t::set_value(::std::string&& value) {
  set_has_value();
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:common.indirect_register_t.value)
}
#endif
inline void indirect_register_t::set_value(const char* value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:common.indirect_register_t.value)
}
inline void indirect_register_t::set_value(const void* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:common.indirect_register_t.value)
}
inline ::std::string* indirect_register_t::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:common.indirect_register_t.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* indirect_register_t::release_value() {
  // @@protoc_insertion_point(field_release:common.indirect_register_t.value)
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void indirect_register_t::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:common.indirect_register_t.value)
}

// -------------------------------------------------------------------

// memory_pol

// optional .common.action addr = 1 [default = DEFAULT];
inline bool memory_pol::has_addr() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void memory_pol::set_has_addr() {
  _has_bits_[0] |= 0x00000001u;
}
inline void memory_pol::clear_has_addr() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void memory_pol::clear_addr() {
  addr_ = 0;
  clear_has_addr();
}
inline ::common::action memory_pol::addr() const {
  // @@protoc_insertion_point(field_get:common.memory_pol.addr)
  return static_cast< ::common::action >(addr_);
}
inline void memory_pol::set_addr(::common::action value) {
  assert(::common::action_IsValid(value));
  set_has_addr();
  addr_ = value;
  // @@protoc_insertion_point(field_set:common.memory_pol.addr)
}

// optional .common.action value = 2 [default = DEFAULT];
inline bool memory_pol::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void memory_pol::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void memory_pol::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void memory_pol::clear_value() {
  value_ = 0;
  clear_has_value();
}
inline ::common::action memory_pol::value() const {
  // @@protoc_insertion_point(field_get:common.memory_pol.value)
  return static_cast< ::common::action >(value_);
}
inline void memory_pol::set_value(::common::action value) {
  assert(::common::action_IsValid(value));
  set_has_value();
  value_ = value;
  // @@protoc_insertion_point(field_set:common.memory_pol.value)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace common

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::common::smt_result> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::common::smt_result>() {
  return ::common::smt_result_descriptor();
}
template <> struct is_proto_enum< ::common::tracing_action> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::common::tracing_action>() {
  return ::common::tracing_action_descriptor();
}
template <> struct is_proto_enum< ::common::action> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::common::action>() {
  return ::common::action_descriptor();
}
template <> struct is_proto_enum< ::common::call_convention_t> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::common::call_convention_t>() {
  return ::common::call_convention_t_descriptor();
}
template <> struct is_proto_enum< ::common::ir_kind_t> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::common::ir_kind_t>() {
  return ::common::ir_kind_t_descriptor();
}
template <> struct is_proto_enum< ::common::solver_t> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::common::solver_t>() {
  return ::common::solver_t_descriptor();
}
template <> struct is_proto_enum< ::common::analysis_direction_t> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::common::analysis_direction_t>() {
  return ::common::analysis_direction_t_descriptor();
}
template <> struct is_proto_enum< ::common::proto_size_t> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::common::proto_size_t>() {
  return ::common::proto_size_t_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_common_2eproto__INCLUDED
